using System;

namespace Python.Runtime
{
    public interface IInterop
    {
        string GetDllName();
        IntPtr PyBytes_FromString(string op);
        int PyBytes_Size(IntPtr op);
        int PyCallable_Check(IntPtr pointer);
        IntPtr PyCFunction_Call(IntPtr func, IntPtr args, IntPtr kw);
        IntPtr PyCFunction_NewEx(IntPtr ml, IntPtr self, IntPtr mod);
        IntPtr PyClass_New(IntPtr bases, IntPtr dict, IntPtr name);
        IntPtr PyDictProxy_New(IntPtr dict);
        void PyDict_Clear(IntPtr pointer);
        IntPtr PyDict_Copy(IntPtr pointer);
        int PyDict_DelItem(IntPtr pointer, IntPtr key);
        int PyDict_DelItemString(IntPtr pointer, string key);
        IntPtr PyDict_GetItem(IntPtr pointer, IntPtr key);
        IntPtr PyDict_GetItemString(IntPtr pointer, string key);
        IntPtr PyDict_Items(IntPtr pointer);
        IntPtr PyDict_Keys(IntPtr pointer);
        IntPtr PyDict_New();
        int PyDict_SetItem(IntPtr pointer, IntPtr key, IntPtr value);
        int PyDict_SetItemString(IntPtr pointer, string key, IntPtr value);
        int PyDict_Size(IntPtr pointer);
        int PyDict_Update(IntPtr pointer, IntPtr other);
        IntPtr PyDict_Values(IntPtr pointer);
        void PyErr_Clear();
        int PyErr_ExceptionMatches(IntPtr exception);
        void PyErr_Fetch(ref IntPtr ob, ref IntPtr val, ref IntPtr tb);
        int PyErr_GivenExceptionMatches(IntPtr ob, IntPtr val);
        void PyErr_NormalizeException(IntPtr ob, IntPtr val, IntPtr tb);
        int PyErr_Occurred();
        void PyErr_Print();
        void PyErr_Restore(IntPtr ob, IntPtr val, IntPtr tb);
        IntPtr PyErr_SetFromErrno(IntPtr ob);
        void PyErr_SetNone(IntPtr ob);
        void PyErr_SetObject(IntPtr ob, IntPtr message);
        void PyErr_SetString(IntPtr ob, string message);
        void PyEval_AcquireThread(IntPtr tstate);
        IntPtr PyEval_EvalCode(IntPtr co, IntPtr globals, IntPtr locals);
        IntPtr PyEval_GetBuiltins();
        IntPtr PyEval_GetGlobals();
        IntPtr PyEval_GetLocals();
        void PyEval_InitThreads();
        void PyEval_ReleaseLock();
        void PyEval_ReleaseThread(IntPtr tstate);
        void PyEval_RestoreThread(IntPtr tstate);
        IntPtr PyEval_SaveThread();
        int PyEval_ThreadsInitialized();
        double PyFloat_AsDouble(IntPtr ob);
        IntPtr PyFloat_FromDouble(double value);
        IntPtr PyFloat_FromString(IntPtr value, IntPtr junk);
        IntPtr PyGILState_Ensure();
        IntPtr PyGILState_GetThisThreadState();
        void PyGILState_Release(IntPtr gs);
        IntPtr PyImport_AddModule(string name);
        IntPtr PyImport_ExecCodeModule(string name, IntPtr code);
        IntPtr PyImport_GetModuleDict();
        IntPtr PyImport_Import(IntPtr name);
        IntPtr PyImport_ImportModule(string name);
        IntPtr PyImport_ReloadModule(IntPtr module);
        IntPtr PyInstance_New(IntPtr cls, IntPtr args, IntPtr kw);
        IntPtr PyInstance_NewRaw(IntPtr cls, IntPtr dict);
        int PyInt_AsLong(IntPtr value);
        IntPtr PyInt_FromString(string value, IntPtr end, int radix);
        int PyInt_GetMax();
        IntPtr PyIter_Next(IntPtr pointer);
        int PyList_Append(IntPtr pointer, IntPtr value);
        IntPtr PyList_AsTuple(IntPtr pointer);
        IntPtr PyList_GetItem(IntPtr pointer, int index);
        IntPtr PyList_GetSlice(IntPtr pointer, int start, int end);
        int PyList_Insert(IntPtr pointer, int index, IntPtr value);
        IntPtr PyList_New(int size);
        int PyList_Reverse(IntPtr pointer);
        int PyList_SetItem(IntPtr pointer, int index, IntPtr value);
        int PyList_SetSlice(IntPtr pointer, int start, int end, IntPtr value);
        int PyList_Size(IntPtr pointer);
        int PyList_Sort(IntPtr pointer);
        int PyLong_AsLong(IntPtr value);
        long PyLong_AsLongLong(IntPtr value);
#pragma warning disable CS3002 // Return type is not CLS-compliant
        uint PyLong_AsUnsignedLong(IntPtr value);
        ulong PyLong_AsUnsignedLongLong(IntPtr value);
#pragma warning restore CS3002 // Return type is not CLS-compliant
        IntPtr PyLong_FromDouble(double value);
        IntPtr PyLong_FromLong(long value);
        IntPtr PyLong_FromLongLong(long value);
        IntPtr PyLong_FromString(string value, IntPtr end, int radix);
#pragma warning disable CS3001 // Argument type is not CLS-compliant
        IntPtr PyLong_FromUnsignedLong(uint value);
        IntPtr PyLong_FromUnsignedLongLong(ulong value);
#pragma warning restore CS3001 // Argument type is not CLS-compliant
        int PyMapping_HasKey(IntPtr pointer, IntPtr key);
        void PyMem_Free(IntPtr ptr);
        IntPtr PyMem_Malloc(int size);
        IntPtr PyMem_Realloc(IntPtr ptr, int size);
        IntPtr PyMethod_Function(IntPtr ob);
        IntPtr PyMethod_New(IntPtr func, IntPtr self, IntPtr cls);
        IntPtr PyMethod_Self(IntPtr ob);
        IntPtr PyModule_Create2(IntPtr module, int apiver);
        IntPtr PyModule_GetDict(IntPtr module);
        string PyModule_GetFilename(IntPtr module);
        string PyModule_GetName(IntPtr module);
        IntPtr PyModule_New(string name);
        IntPtr PyNumber_Add(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_And(IntPtr o1, IntPtr o2);
        bool PyNumber_Check(IntPtr ob);
        IntPtr PyNumber_Divide(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Float(IntPtr ob);
        IntPtr PyNumber_InPlaceAdd(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceAnd(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceDivide(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceLshift(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceMultiply(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceOr(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlacePower(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceRemainder(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceRshift(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceSubtract(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_InPlaceXor(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Int(IntPtr ob);
        IntPtr PyNumber_Invert(IntPtr o1);
        IntPtr PyNumber_Long(IntPtr ob);
        IntPtr PyNumber_Lshift(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Multiply(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Negative(IntPtr o1);
        IntPtr PyNumber_Or(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Positive(IntPtr o1);
        IntPtr PyNumber_Power(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Remainder(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Rshift(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Subtract(IntPtr o1, IntPtr o2);
        IntPtr PyNumber_Xor(IntPtr o1, IntPtr o2);
        IntPtr PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw);
        IntPtr PyObject_CallObject(IntPtr pointer, IntPtr args);
        int PyObject_DelItem(IntPtr pointer, IntPtr key);
        IntPtr PyObject_Dir(IntPtr pointer);
        void PyObject_GC_Del(IntPtr tp);
        IntPtr PyObject_GC_New(IntPtr tp);
        void PyObject_GC_Track(IntPtr tp);
        void PyObject_GC_UnTrack(IntPtr tp);
        IntPtr PyObject_GenericGetAttr(IntPtr obj, IntPtr name);
        int PyObject_GenericSetAttr(IntPtr obj, IntPtr name, IntPtr value);
        IntPtr PyObject_GetAttr(IntPtr pointer, IntPtr name);
        IntPtr PyObject_GetAttrString(IntPtr pointer, string name);
        IntPtr PyObject_GetItem(IntPtr pointer, IntPtr key);
        IntPtr PyObject_GetIter(IntPtr op);
        int PyObject_HasAttr(IntPtr pointer, IntPtr name);
        int PyObject_HasAttrString(IntPtr pointer, string name);
        IntPtr PyObject_Hash(IntPtr op);
        int PyObject_IsInstance(IntPtr ob, IntPtr type);
        int PyObject_IsSubclass(IntPtr ob, IntPtr type);
        int PyObject_IsTrue(IntPtr pointer);
        int PyObject_Not(IntPtr pointer);
        IntPtr PyObject_Repr(IntPtr pointer);
        int PyObject_RichCompareBool(IntPtr value1, IntPtr value2, int opid);
        int PyObject_SetAttr(IntPtr pointer, IntPtr name, IntPtr value);
        int PyObject_SetAttrString(IntPtr pointer, string name, IntPtr value);
        int PyObject_SetItem(IntPtr pointer, IntPtr key, IntPtr value);
        int PyObject_Size(IntPtr pointer);
        IntPtr PyObject_Str(IntPtr pointer);
        IntPtr PyObject_Unicode(IntPtr pointer);
        int PyRun_SimpleString(string code);
        IntPtr PyRun_String(string code, IntPtr st, IntPtr globals, IntPtr locals);
        bool PySequence_Check(IntPtr pointer);
        IntPtr PySequence_Concat(IntPtr pointer, IntPtr other);
        int PySequence_Contains(IntPtr pointer, IntPtr item);
        int PySequence_Count(IntPtr pointer, IntPtr value);
        int PySequence_DelItem(IntPtr pointer, int index);
        int PySequence_DelSlice(IntPtr pointer, int i1, int i2);
        IntPtr PySequence_GetItem(IntPtr pointer, int index);
        IntPtr PySequence_GetSlice(IntPtr pointer, int i1, int i2);
        int PySequence_Index(IntPtr pointer, IntPtr item);
        IntPtr PySequence_List(IntPtr pointer);
        IntPtr PySequence_Repeat(IntPtr pointer, int count);
        int PySequence_SetItem(IntPtr pointer, int index, IntPtr value);
        int PySequence_SetSlice(IntPtr pointer, int i1, int i2, IntPtr v);
        int PySequence_Size(IntPtr pointer);
        IntPtr PySequence_Tuple(IntPtr pointer);
        IntPtr PyString_FromStringAndSize(string value, int size);
        IntPtr PySys_GetObject(string name);
        void PySys_SetArgvEx(int argc, string[] argv, int updatepath);
        int PySys_SetObject(string name, IntPtr ob);
        IntPtr PyThreadState_Get();
        IntPtr PyThreadState_New(IntPtr istate);
        IntPtr PyThreadState_Swap(IntPtr key);
        IntPtr PyThread_get_key_value(IntPtr key);
        int PyThread_get_thread_ident();
        int PyThread_set_key_value(IntPtr key, IntPtr value);
        IntPtr PyTuple_GetItem(IntPtr pointer, int index);
        IntPtr PyTuple_GetSlice(IntPtr pointer, int start, int end);
        IntPtr PyTuple_New(int size);
        int PyTuple_SetItem(IntPtr pointer, int index, IntPtr value);
        int PyTuple_Size(IntPtr pointer);
        IntPtr PyType_GenericAlloc(IntPtr type, int n);
        IntPtr PyType_GenericNew(IntPtr type, IntPtr args, IntPtr kw);
        bool PyType_IsSubtype(IntPtr t1, IntPtr t2);
        void PyType_Modified(IntPtr type);
        int PyType_Ready(IntPtr type);
        IntPtr PyUnicode_AsUnicode(IntPtr ob);
        IntPtr PyUnicode_FromEncodedObject(IntPtr ob, IntPtr enc, IntPtr err);
        IntPtr PyUnicode_FromKindAndData(int kind, string s, int size);
        IntPtr PyUnicode_FromObject(IntPtr ob);
        IntPtr PyUnicode_FromOrdinal(int c);
        IntPtr PyUnicode_FromStringAndSize(IntPtr value, int size);
        int PyUnicode_GetSize(IntPtr ob);
        IntPtr Py_CompileString(string code, string file, IntPtr tok);
        void Py_DecRef(IntPtr ob);
        void Py_EndInterpreter(IntPtr threadState);
        void Py_Finalize();
        IntPtr Py_GetBuildInfo();
        IntPtr Py_GetCompiler();
        IntPtr Py_GetCopyright();
        IntPtr Py_GetPath();
        IntPtr Py_GetPlatform();
        IntPtr Py_GetProgramName();
        IntPtr Py_GetPythonHome();
        IntPtr Py_GetVersion();
        void Py_IncRef(IntPtr ob);
        void Py_Initialize();
        int Py_IsInitialized();
        int Py_Main(int argc, string[] argv);
        IntPtr Py_NewInterpreter();
        void Py_SetPath(IntPtr home);
        void Py_SetProgramName(IntPtr name);
        void Py_SetPythonHome(IntPtr home);
#pragma warning disable CS3008 // Identifier is not CLS-compliant
        IntPtr _PyObject_GetDictPtr(IntPtr obj);
        IntPtr _PyType_Lookup(IntPtr type, IntPtr name);
#pragma warning restore CS3008 // Identifier is not CLS-compliant
        IntPtr PyInt_FromLong(IntPtr value);
    }
}
